<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Antenna constants -->
  <xacro:property name="antenna_len" value="0.19" />
  <xacro:property name="antenna_r" value="0.005" />
  <xacro:property name="antenna_x" value="-0.645" />  
  <!-- Antenna constants -->

  <!-- Inertia Macros -->
  <xacro:include filename="$(find jetbot_diff_drive)/urdf/includes/gazebo/inertias.xacro" />  
  <!-- Inertia Macros -->

  <!-- Left and Right Antenna Macro -->
  <xacro:macro name="antenna" params="prefix reflect">
  <link name="${prefix}_antenna">
    <visual>
      <origin xyz="0 0 ${antenna_len/2}"/>
      <geometry>
        <cylinder length="${antenna_len}" radius="${antenna_r}"/>
      </geometry>
      <material name="black"/>      
    </visual>
    <collision>
      <origin xyz="0 0 ${antenna_len/2}"/>
      <geometry>
        <cylinder length="${antenna_len}" radius="${antenna_r}"/>
      </geometry>
    </collision>    
    <xacro:cylinder_inertia mass="0.6" r="${antenna_r}" h="${antenna_len}" />    
  </link>
  <joint name="base_${prefix}_antenna_joint" type="fixed">
    <parent link="base_link"/>
    <child link="${prefix}_antenna"/>
    <origin xyz="-${(base_len/2 - antenna_r)} ${reflect*(antenna_r + 0.0375)} 0.0305"/>
  </joint>

  <link name="${prefix}_antenna_top">
    <visual>
      <geometry>
        <sphere radius="${antenna_r}"/>
      </geometry> 
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${antenna_r}"/>
      </geometry>
    </collision>   
    <xacro:sphere_inertia mass="0.06" r="${antenna_r}" />    
  </link>
  <joint name="${prefix}_antenna_top_joint" type="fixed">
    <origin xyz="0 0 ${antenna_len}"/>
    <parent link="${prefix}_antenna"/>
    <child link="${prefix}_antenna_top"/>
  </joint>
  </xacro:macro>
  <!-- Left and Right Antenna Macro -->

</robot> 