<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- MTK3339 Constants -->
  <xacro:property name="mtk_depth" value="0.0044" />
  <xacro:property name="mtk_width" value="0.016" />
  <xacro:property name="mtk_height" value="0.016" />
  <xacro:property name="mtk_mass" value="0.0085" />    
  <!-- MTK3339 constants -->

  <!-- Inertias Macros -->
  <xacro:include filename="$(find jetbot_diff_drive)/urdf/includes/gazebo/inertias.xacro" />
  <!-- Inertias Macros -->

  <xacro:include filename="$(find jetbot_diff_drive)/urdf/includes/gazebo/gps.gazebo.xacro" />

  <!-- GPS MTK3339 -->
  <xacro:macro name="sensor_gps" params="name:=mtk3339 topic_ns:=gps parent *origin">

    <joint name="${name}_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${name}_link"/>
      <xacro:insert_block name="origin" />
    </joint>

    <link name="${name}_link">
      <visual>
        <origin xyz="-${mtk_width/2} ${mtk_height/2} 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <mesh filename="package://jetbot_diff_drive/meshes/gps/mtk3339.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="yellow"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${mtk_depth/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${mtk_width} ${mtk_height} ${mtk_depth}"/>
        </geometry>
      </collision>
      <xacro:cuboid_inertia mass="${mtk_mass}" x="${mtk_width}" y="${mtk_height}" z="${mtk_depth}" />
    </link>
    <!-- GPS Plugin -->
    <xacro:gazebo_gps gps_name="${name}_gps" reference_link="${name}_link" topic_ns="${topic_ns}" />    
    <!-- GPS Plugin -->
  </xacro:macro>
</robot>